apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: catalogservice
  name: catalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: catalogservice
    spec:
      containers:
      - image: catalogservice
        name: catalogservice
        resources: {}
status: {}
