apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalogservice
  name: catalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogservice
  template:
    metadata:
      labels:
        app: catalogservice
    spec:
      containers:
      - image: catalogservice:v1
        name: catalogservice
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
