apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalogservice
  name: catalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogservice
  template:
    metadata:
      labels:
        app: catalogservice
    spec:
      containers:
      - image: catalogservice:v1
        name: catalogservice
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        volumeMounts:
        - name: videos-storage
          mountPath: /Storage/Videos  # Caminho onde serão armazenados os vídeos dentro do container
        - name: thumbnails-storage
          mountPath: /Storage/Thumbnails  # Caminho onde serão armazenadas as thumbnails dentro do container
      volumes:
      - name: videos-storage
        persistentVolumeClaim:
          claimName: videos-storage-claim
      - name: thumbnails-storage
        persistentVolumeClaim:
          claimName: thumbnails-storage-claim