apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamingservice
  name: streamingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamingservice
  template:
    metadata:
      labels:
        app: streamingservice
    spec:
      containers:
      - image: streamingservice:v1
        name: streamingservice
        ports:
        - containerPort: 6000
        env:
        - name: FLASK_ENV
          value: "production"