apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: uploadservice
  name: uploadservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploadservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: uploadservice
    spec:
      containers:
      - image: uploadservice
        name: uploadservice
        resources: {}
status: {}
