apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: uploadservice
  name: uploadservice
spec:
  ports:
  - name: 7000-7000
    port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: uploadservice
  type: NodePort
status:
  loadBalancer: {}
