apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uploadservice
  name: uploadservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploadservice
  template:
    metadata:
      labels:
        app: uploadservice
    spec:
      containers:
      - image: uploadservice:v1
        name: uploadservice
        ports:
        - containerPort: 7000
        env:
        - name: FLASK_ENV
          value: "production"
